-- Database Schema and Seed Data
-- Generated by Antigravity

BEGIN;

-- --------------------------------------------------------------------------------
-- 1. Table: hospitals
-- --------------------------------------------------------------------------------
CREATE TABLE hospitals (
    id TEXT PRIMARY KEY,
    hospital_name TEXT NOT NULL,
    phone TEXT,
    type TEXT,
    address TEXT,
    city TEXT,
    pincode TEXT,
    email TEXT,
    blood_types TEXT[] -- Storing blood types as a text array
);

-- --------------------------------------------------------------------------------
-- 2. Table: users
-- --------------------------------------------------------------------------------
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    role TEXT CHECK (role IN ('donor', 'patient', 'admin')), -- Added simple check for better data quality
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    location TEXT,
    blood_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    phone_number TEXT
);

-- --------------------------------------------------------------------------------
-- 3. Table: notifications
-- --------------------------------------------------------------------------------
-- Note: Changed 'id' from UUID to TEXT to match the provided sample data 'N001', etc.
-- If UUIDs are strictly required, remove the provided IDs and use DEFAULT gen_random_uuid().
CREATE TABLE notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('blood_request', 'system', 'donation_reminder')),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    urgency TEXT NOT NULL CHECK (urgency IN ('Low', 'Medium', 'High', 'Critical')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    blood_request_id TEXT,
    distance DECIMAL
);

-- --------------------------------------------------------------------------------
-- Seed Data: hospitals
-- --------------------------------------------------------------------------------
INSERT INTO hospitals (id, hospital_name, phone, type, address, city, pincode, email, blood_types) VALUES
('H001', 'Apollo Hospital', '040-23551234', 'Multi-speciality', 'Jubilee Hills', 'Hyderabad', '500033', 'apollo.hyderabad@apollo.com', ARRAY['A+','A−','B+','O+','O−']),
('H002', 'Manipal Hospital', '080-25021234', 'Multi-speciality', 'Old Airport Road', 'Bengaluru', '560017', 'info.blr@manipal.com', ARRAY['O+','B+','AB+','A+','O−']),
('H003', 'Care Hospital', '040-67891234', 'Emergency', 'Banjara Hills', 'Hyderabad', '500034', 'care.emergency@care.com', ARRAY['A+','B−','O+','AB−']),
('H004', 'Fortis Hospital', '044-66001234', 'Multi-speciality', 'Vadapalani', 'Chennai', '600026', 'contact@fortischennai.com', ARRAY['A+','O+','B+','AB+']),
('H005', 'KIMS Hospital', '040-44881234', 'Trauma Center', 'Secunderabad', 'Hyderabad', '500003', 'emergency@kimshospitals.com', ARRAY['O−','A−','B−']),
('H006', 'Aster CMI Hospital', '080-43420123', 'Emergency', 'Hebbal', 'Bengaluru', '560024', 'emergency@astercmi.com', ARRAY['A+','O+','AB−','B+']),
('H007', 'Continental Hospital', '040-67001234', 'Multi-speciality', 'Gachibowli', 'Hyderabad', '500032', 'support@continentalhospitals.com', ARRAY['A+','B+','O−']),
('H008', 'Rajiv Gandhi Govt Hospital', '044-25305000', 'Government', 'Park Town', 'Chennai', '600003', 'info@rgggh.org', ARRAY['A+','B+','O+','AB+']),
('H009', 'St. John’s Hospital', '080-49466000', 'Multi-speciality', 'Koramangala', 'Bengaluru', '560034', 'care@stjohnsblr.com', ARRAY['A−','O+','O−','B+']),
('H010', 'Sunshine Hospital', '040-65991234', 'Emergency', 'Gachibowli', 'Hyderabad', '500032', 'contact@sunshinehospitals.in', ARRAY['O+','A+','AB+','B−']);

-- --------------------------------------------------------------------------------
-- Seed Data: users
-- --------------------------------------------------------------------------------
INSERT INTO users (id, role, email, full_name, location, blood_type, created_at, phone_number) VALUES
('U001', 'donor', 'arjun.reddy@example.com', 'Arjun Reddy', 'Hyderabad', 'A+', '2025-01-10 10:20:00+00', '9876543210'),
('U002', 'patient', 'sneha.kapoor@example.com', 'Sneha Kapoor', 'Bengaluru', 'O+', '2025-01-09 11:30:00+00', '9876501234'),
('U003', 'donor', 'rahul.mehta@example.com', 'Rahul Mehta', 'Chennai', 'B+', '2025-01-11 09:10:00+00', '9988776655'),
('U004', 'patient', 'ananya.sharma@example.com', 'Ananya Sharma', 'Hyderabad', 'A−', '2025-01-12 15:45:00+00', '9123456780'),
('U005', 'donor', 'vivek.nair@example.com', 'Vivek Nair', 'Kochi', 'O−', '2025-01-08 08:00:00+00', '9090909090'),
('U006', 'donor', 'meena.reddy@example.com', 'Meena Reddy', 'Hyderabad', 'AB+', '2025-01-11 14:40:00+00', '9000012345'),
('U007', 'patient', 'praveen.kumar@example.com', 'Praveen Kumar', 'Bengaluru', 'B−', '2025-01-10 18:20:00+00', '9012345678'),
('U008', 'donor', 'asha.varma@example.com', 'Asha Varma', 'Chennai', 'AB−', '2025-01-07 17:15:00+00', '9812345670'),
('U009', 'patient', 'kiran.mohan@example.com', 'Kiran Mohan', 'Hyderabad', 'O+', '2025-01-05 09:20:00+00', '9876123450'),
('U010', 'donor', 'sathish.patel@example.com', 'Sathish Patel', 'Bengaluru', 'A−', '2025-01-13 12:00:00+00', '9800001122');

-- --------------------------------------------------------------------------------
-- Seed Data: notifications
-- --------------------------------------------------------------------------------
INSERT INTO notifications (id, user_id, type, title, message, read, urgency, created_at, blood_request_id, distance) VALUES
('N001', 'U002', 'blood_request', 'Urgent Blood Needed', 'O+ blood required at Manipal Hospital.', false, 'High', '2025-01-10 10:40:00+00', 'BR001', 3.2),
('N002', 'U001', 'system', 'Donation Eligibility', 'You are eligible to donate again.', false, 'Low', '2025-01-11 09:00:00+00', NULL, NULL),
('N003', 'U004', 'blood_request', 'Critical Request', 'A− blood urgently required at Apollo Hospital.', false, 'Critical', '2025-01-12 08:50:00+00', 'BR002', 1.1),
('N004', 'U003', 'donation_reminder', 'Reminder to Donate', 'You have not donated in 6 months.', true, 'Medium', '2025-01-09 15:30:00+00', NULL, NULL),
('N005', 'U009', 'blood_request', 'Emergency Need', 'O+ blood needed immediately near you.', false, 'High', '2025-01-10 19:20:00+00', 'BR003', 2.5);

COMMIT;
