-- Real-Time Notification System Setup
-- Generated by Antigravity

BEGIN;

-- --------------------------------------------------------------------------------
-- 1. Create table `blood_requests` (Was missing in previous schema)
-- --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blood_requests (
    id TEXT PRIMARY KEY,
    requester_id TEXT REFERENCES users(id),
    blood_type TEXT NOT NULL,
    status TEXT CHECK (status IN ('Pending', 'Accepted', 'Fulfilled', 'Cancelled')) DEFAULT 'Pending',
    donor_id TEXT REFERENCES users(id), -- The donor who accepted
    hospital_id TEXT REFERENCES hospitals(id),
    units_needed INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------------------------------------------
-- 2. Update `notifications` table for email tracking
-- --------------------------------------------------------------------------------
ALTER TABLE notifications 
ADD COLUMN IF NOT EXISTS sent_status TEXT CHECK (sent_status IN ('pending', 'sent', 'failed')) DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS email_result TEXT;

-- --------------------------------------------------------------------------------
-- 3. Trigger Function: Notify Channel on New Notification
-- --------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_new_notification()
RETURNS TRIGGER AS $$
BEGIN
    -- Send payload to 'notification_channel'
    -- Payload includes the ID to keep it lightweight, or full row JSON
    PERFORM pg_notify('notification_channel', row_to_json(NEW)::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_notify_new_notification
AFTER INSERT ON notifications
FOR EACH ROW
EXECUTE FUNCTION notify_new_notification();

-- --------------------------------------------------------------------------------
-- 4. Trigger Function: Create Notification on Blood Request Acceptance
-- --------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION handle_blood_request_acceptance()
RETURNS TRIGGER AS $$
DECLARE
    requester_name TEXT;
    donor_name TEXT;
BEGIN
    -- Check if status changed to 'Accepted' OR donor_id was just set
    IF (OLD.status IS DISTINCT FROM 'Accepted' AND NEW.status = 'Accepted') OR
       (OLD.donor_id IS NULL AND NEW.donor_id IS NOT NULL) THEN
       
        -- Get names for better message
        SELECT full_name INTO requester_name FROM users WHERE id = NEW.requester_id;
        SELECT full_name INTO donor_name FROM users WHERE id = NEW.donor_id;

        -- Insert notification for the Requester (Patient)
        INSERT INTO notifications (
            id, 
            user_id, 
            type, 
            title, 
            message, 
            urgency, 
            blood_request_id,
            sent_status -- Marked as pending for the email worker to pick up
        )
        VALUES (
            'N' || to_char(NOW(), 'YYYYMMDDHHMISSMS'), -- Simple ID tracking or use UUID
            NEW.requester_id,
            'system',
            'Blood Request Accepted!',
            'Good news! A donor (' || COALESCE(donor_name, 'Anonymous') || ') has accepted your request for ' || NEW.blood_type || ' blood.',
            'High',
            NEW.id,
            'pending'
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_blood_request_accepted
AFTER UPDATE ON blood_requests
FOR EACH ROW
EXECUTE FUNCTION handle_blood_request_acceptance();

-- --------------------------------------------------------------------------------
-- 5. Seed Data for Testing
-- --------------------------------------------------------------------------------
-- Insert a sample blood request
INSERT INTO blood_requests (id, requester_id, blood_type, status, hospital_id)
VALUES ('BR_TEST_01', 'U002', 'O+', 'Pending', 'H001')
ON CONFLICT (id) DO NOTHING;

COMMIT;

-- --------------------------------------------------------------------------------
-- TEST INSTRUCTIONS used by User later:
-- Run this command to simulate a donor accepting the request:
-- UPDATE blood_requests 
-- SET status = 'Accepted', donor_id = 'U001' 
-- WHERE id = 'BR_TEST_01';
-- --------------------------------------------------------------------------------
